version: '3'
services:
  morphocluster:
    build:
      context: .
      dockerfile: docker/morphocluster/Dockerfile
    ports:
      # Expose port 8000 (web service)
      - "8000:8000"
      ## Expose port 22 for external SSH access:
      #- "8022:22"
    depends_on:
      - postgres
      - redis-lru
    restart: unless-stopped
    volumes:
      - morphocluster-data:/data
      - ${PWD}/docker/morphocluster/authorized_keys:/authorized_keys:ro
    environment:
      # Store command history in the data volume
      - HISTSIZE=-1
      - HISTFILESIZE=-1
      - HISTFILE=/data/.bash_history
    # # Uncomment this block to use the host's GPU inside the container
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - capabilities:
    #           - gpu
  postgres:
    build: docker/postgresql
    environment:
      POSTGRES_USER: morphocluster
      POSTGRES_PASSWORD: morphocluster
      POSTGRES_DB: morphocluster
    ports:
      - "5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    # Increase shared memory to allow for big queries
    shm_size: '2gb'
    restart: unless-stopped

  redis-rq:
    image: "redis:5-alpine"
    ports:
      - "6379"
    restart: unless-stopped

  redis-lru:
    build: docker/redis-lru
    ports:
      - "6379"
    restart: unless-stopped

volumes:
  postgres-data:
    ## Example: Store PostgreSQL data in a host directory
    # driver: local
    # driver_opts:
    #   o: bind
    #   type: none
    #    
    #   # Replace with your own configuration
    #   device: /data/morphocluster/data
  morphocluster-data:
    ## Example: Store application data in a host directory
    # driver: local
    # driver_opts:
    #   o: bind
    #   type: none
    #   device: /data/morphocluster/data