name: morphocluster
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  # Conda packages
  - python=3.10
  - numpy=1.22
  - pandas
  - h5py=3.6
  - scikit-learn=1.0
  - scipy
  - pip
  - hdbscan
  # - nodejs #=17
  # - openssl < 3.0.0 # OpenSSL 3.0.0 removed some encryption algorithms needed for frontend build (md4)
  - Pillow
  - pytorch
  - torchvision
  - hiredis
  - joblib==1.1.0 # See https://github.com/scikit-learn-contrib/hdbscan/issues/562

  - pip:
    # pip packages required to run MorphoCluster but not specified by setup.py
    - gunicorn
