name: base
category: dev
channels:
  - conda-forge
  - defaults
dependencies:
  - git  # Also installed from Ubuntu, but this is newer.
  - pre-commit
  - black
  - isort
  - pipx
  - mamba
  - ipykernel  # Jupyter notebooks in VS Code
  - flake8
  - pytest
  - pytest-cov
  - requests
  - make # For docs
  - pip
  - pip:
    - lovely-pytest-docker
    - -e docs/requirements.txt