name: morphocluster
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  # Conda packages
  - python=3.10
  - numpy=1.22
  - pandas
  - h5py=3.6
  - scikit-learn=1.0
  - scipy
  - pip
  - hdbscan
  - nodejs #=17
  - openssl < 3.0.0 # OpenSSL 3.0.0 removed some encryption algorithms needed for frontend build (md4)
  - Pillow
  - pytorch
  - torchvision
  - hiredis
  # Replace by the correction version of cudatoolkit to enable GPU feature extraction,
  # e.g. "cudatoolkit=10.2"
  - cpuonly

  - pip:
    # pip packages required to run MorphoCluster but not specified by setup.py
    - gunicorn
